# Generated by Django 5.2 on 2025-05-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='advance_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='is_advance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='is_full_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
