# Generated by Django 5.2 on 2025-05-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_rental_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='balance_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='balance_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
